// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0zRm-ki76hTXzIerz6ZZ5-zCwSstMeRo',
    appId: '1:186464570202:web:421fe07df098456b0ec163',
    messagingSenderId: '186464570202',
    projectId: 'tennisapp-87e2e',
    authDomain: 'tennisapp-87e2e.firebaseapp.com',
    storageBucket: 'tennisapp-87e2e.appspot.com',
    measurementId: 'G-73PGC9P31W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi62T_hzUKYRabUY4aFwlaEG394EIYmiQ',
    appId: '1:186464570202:android:6a445e63d86afd800ec163',
    messagingSenderId: '186464570202',
    projectId: 'tennisapp-87e2e',
    storageBucket: 'tennisapp-87e2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-EXzWHMrNxpzyUY8jb3q8TQzxFo4hhBQ',
    appId: '1:186464570202:ios:b4357b6fbfb917880ec163',
    messagingSenderId: '186464570202',
    projectId: 'tennisapp-87e2e',
    storageBucket: 'tennisapp-87e2e.appspot.com',
    iosClientId: '186464570202-kas74oil6ahe57vh3m9vrrvefvsbn04q.apps.googleusercontent.com',
    iosBundleId: 'com.example.appApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-EXzWHMrNxpzyUY8jb3q8TQzxFo4hhBQ',
    appId: '1:186464570202:ios:f110afdfd8a6ff480ec163',
    messagingSenderId: '186464570202',
    projectId: 'tennisapp-87e2e',
    storageBucket: 'tennisapp-87e2e.appspot.com',
    iosBundleId: 'com.example.appApk.RunnerTests',
  );
}
